-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 10:06:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sdebookingsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sdebookingsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sdebookingsystem` DEFAULT CHARACTER SET latin1 ;
USE `sdebookingsystem` ;

-- -----------------------------------------------------
-- Table `sdebookingsystem`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`user_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_rank` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`users` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_group_id` INT(11) NOT NULL,
  `disabled` INT(11) NOT NULL DEFAULT '1',
  `verified` INT(11) NOT NULL DEFAULT '0',
  `verifykey` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC),
  INDEX `user_group_id` (`user_group_id` ASC),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `sdebookingsystem`.`user_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`wish_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`wish_list` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rerserved_date` DATE NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `reminder_date` DATE NOT NULL,
  `godkendt` TINYINT(4) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `wish_list_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sdebookingsystem`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`product_rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`product_rentals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `wish_list_id` INT(11) NOT NULL,
  `available` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `wish_list_id` (`wish_list_id` ASC),
  CONSTRAINT `product_rentals_ibfk_1`
    FOREIGN KEY (`wish_list_id`)
    REFERENCES `sdebookingsystem`.`wish_list` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`location_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`location_room` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `room` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`supplier_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`supplier_company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `call_number` INT(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`product_school_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`product_school_address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `school_name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zip_code` INT(4) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`school_address_short`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`school_address_short` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_name_short` VARCHAR(45) NOT NULL,
  `product_school_address_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_school_address_id` (`product_school_address_id` ASC),
  CONSTRAINT `school_address_short_ibfk_1`
    FOREIGN KEY (`product_school_address_id`)
    REFERENCES `sdebookingsystem`.`product_school_address` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`school_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`school_products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `movable` VARCHAR(3) NOT NULL,
  `supplier_company_id` INT(11) NOT NULL,
  `school_name_short_id` INT(11) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `created_by` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `created_by`),
  INDEX `category_id` (`category_id` ASC),
  INDEX `supplier_company_id` (`supplier_company_id` ASC),
  INDEX `school_name_short_id` (`school_name_short_id` ASC),
  INDEX `fk_school_products_users1_idx` (`created_by` ASC),
  CONSTRAINT `fk_school_products_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `sdebookingsystem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_products_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `sdebookingsystem`.`category` (`id`),
  CONSTRAINT `school_products_ibfk_2`
    FOREIGN KEY (`supplier_company_id`)
    REFERENCES `sdebookingsystem`.`supplier_company` (`id`),
  CONSTRAINT `school_products_ibfk_3`
    FOREIGN KEY (`school_name_short_id`)
    REFERENCES `sdebookingsystem`.`school_address_short` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`product_location_type_svf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`product_location_type_svf` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `nr` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`product_location_type_thp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`product_location_type_thp` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `nr` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`status_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`status_report` (
  `id` INT(11) NOT NULL,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`product_unit_e`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`product_unit_e` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `products_id` INT(11) NOT NULL,
  `location_room_id` INT(11) NOT NULL,
  `product_location_type_svf_id` INT(11) NOT NULL,
  `product_location_type_thp_id` INT(11) NOT NULL,
  `unit_number` VARCHAR(20) NOT NULL,
  `current_status_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `location_room_id` (`location_room_id` ASC),
  INDEX `products_id` (`products_id` ASC),
  INDEX `product_location_type_svf_id` (`product_location_type_svf_id` ASC),
  INDEX `product_location_type_thp_id` (`product_location_type_thp_id` ASC),
  INDEX `current_status_id` (`current_status_id` ASC),
  CONSTRAINT `product_unit_e_ibfk_1`
    FOREIGN KEY (`location_room_id`)
    REFERENCES `sdebookingsystem`.`location_room` (`id`),
  CONSTRAINT `product_unit_e_ibfk_2`
    FOREIGN KEY (`products_id`)
    REFERENCES `sdebookingsystem`.`school_products` (`id`),
  CONSTRAINT `product_unit_e_ibfk_3`
    FOREIGN KEY (`product_location_type_svf_id`)
    REFERENCES `sdebookingsystem`.`product_location_type_svf` (`id`),
  CONSTRAINT `product_unit_e_ibfk_4`
    FOREIGN KEY (`product_location_type_thp_id`)
    REFERENCES `sdebookingsystem`.`product_location_type_thp` (`id`),
  CONSTRAINT `product_unit_e_ibfk_5`
    FOREIGN KEY (`current_status_id`)
    REFERENCES `sdebookingsystem`.`status_report` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`connection_product_rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`connection_product_rentals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_rentals_id` INT(11) NOT NULL,
  `product_unit_e_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_rentals_id` (`product_rentals_id` ASC),
  INDEX `product_unit_e_id` (`product_unit_e_id` ASC),
  CONSTRAINT `connection_product_rentals_ibfk_1`
    FOREIGN KEY (`product_rentals_id`)
    REFERENCES `sdebookingsystem`.`product_rentals` (`id`),
  CONSTRAINT `connection_product_rentals_ibfk_2`
    FOREIGN KEY (`product_unit_e_id`)
    REFERENCES `sdebookingsystem`.`product_unit_e` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`connection_product_wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`connection_product_wishlist` (
  `wish_list_id` INT(11) NOT NULL,
  `school_products_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  INDEX `wish_list_id` (`wish_list_id` ASC),
  INDEX `school_products_id` (`school_products_id` ASC),
  CONSTRAINT `connection_product_wishlist_ibfk_1`
    FOREIGN KEY (`wish_list_id`)
    REFERENCES `sdebookingsystem`.`wish_list` (`id`),
  CONSTRAINT `connection_product_wishlist_ibfk_2`
    FOREIGN KEY (`school_products_id`)
    REFERENCES `sdebookingsystem`.`school_products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sdebookingsystem`.`worker_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sdebookingsystem`.`worker_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone_number` INT(8) NOT NULL,
  `supplier_company_id` INT(11) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT 'Ingen Email',
  PRIMARY KEY (`id`),
  INDEX `supplier_company_id` (`supplier_company_id` ASC),
  CONSTRAINT `worker_info_ibfk_1`
    FOREIGN KEY (`supplier_company_id`)
    REFERENCES `sdebookingsystem`.`supplier_company` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
